name = "bigints"
description = ""
version = "0.1.0-dev"

authors = ["Cesar SAGAERT"]
maintainers = ["Cesar SAGAERT <sagaert@adacore.com>"]
maintainers-logins = ["AldanTanneo"]
licenses = "MIT"
website = ""
tags = []

[build-switches]
"*".ada_version = "Ada2022"
development.optimization = ["-O3"]
release.runtime_checks = "none"

[[depends-on]]
gnatprove = "^14.1"

[[actions]]
type = "test"
command = ["alr", "build"]

[[actions]]
type = "test"
command = ["alr", "gnatprove", "--warnings=error"]

[[actions]]
type = "test"
command = ["./run.sh"]
directory = "tests"
