name = "bigints"
description = ""
version = "0.1.0"

authors = ["Cesar SAGAERT"]
maintainers = ["Cesar SAGAERT <sagaert@adacore.com>"]
maintainers-logins = ["AldanTanneo"]
licenses = "MIT"
website = "https://github.com/AldanTanneo/bigints"
tags = []

[build-switches]
"*".ada_version = "Ada2022"
development.optimization = ["-O3"]
release.runtime_checks = "none"
